[package]
name = "basic_coin"
version = "1.0.0"
edition = "2024.beta"

[dependencies]
MoveStdlib = { git = "https://github.com/move-language/move.git", subdir = "language/move-stdlib", rev = "main" }

[addresses]
std = "0x1"
my_addr = "0x1" 