name: Deploy mdBook to GitHub Pages

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download latest mdBook binary
        run: |
          LATEST_URL=$(curl -s https://api.github.com/repos/rust-lang/mdBook/releases/latest \
            | grep browser_download_url \
            | grep x86_64-unknown-linux-gnu.tar.gz \
            | cut -d '"' -f 4)
          wget "$LATEST_URL" -O mdbook-latest.tar.gz
          tar -xzf mdbook-latest.tar.gz
          sudo mv mdbook /usr/local/bin/
          mdbook --version

      - name: Build the book
        run: mdbook build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
          publish_branch: gh-pages
